export { default as Home } from './home/Home';
export { default as Projects } from './projects/Projects';
export { default as Project } from './project/Project';
export { default as Clients } from './Clients/Clients';
export { default as Client } from './Client/Client';
export { default as Activities } from './Activities/Activities';
export { default as Activity } from './Activity/Activity';
export { default as Support } from './support/Support';
export { default as Inquiry } from './Inquiry/Inquiry';
