// import HomeIcon  from '@mui/icons-material/Home';
// import BusinessCenterIcon from '@mui/icons-material/BusinessCenter';
// import PersonIcon from '@mui/icons-material/Person';
// import HistoryIcon from '@mui/icons-material/History';
// import QuestionAnswerIcon from '@mui/icons-material/QuestionAnswer';
// import ContactSupportIcon from '@mui/icons-material/ContactSupport';
// import { SvgIconProps } from '@mui/material/SvgIcon';


// interface MenuItem {
//   title: string;
//   url: string;
//   icon: any;
// }

// メニューデータ
export const MenuData = [
  {
    id: 1,
    title: 'ホーム',
    url: '/',
    // icon: <HomeIcon />,
  },
  {
    id: 2,
    title: '案件',
    url: '/projects',
    // icon: <BusinessCenterIcon/>,
  },
  {
    id: 3,
    title: '顧客',
    url: '/clients',
    // icon: <PersonIcon/>,
  },
  {
    id: 4,
    title: '活動履歴',
    url: '/activities',
    // icon: <HistoryIcon/>,
  },
  {
    id: 5,
    title: '問い合わせ',
    url: '/inquiry',
    // icon: <QuestionAnswerIcon/>,
  },
  {
    id: 6,
    title: 'FAQ',
    url: '/support',
    // icon: <ContactSupportIcon/>,
  },
];

// 案件データ
export const projectData = [
  {
    id: 1,
    project: '金都運総研営業支援ツール案件',
    client: '金都運総研',
    department: '情報システム部',
    pic: '下山 達士',
    detail: '法人向け営業チームにて、エクセル管理している案件管理、顧客管理をシステム化したいというご要望。\n納期は年度内をご希望。',
    firstMeetingDate: '2018/01/11',
    negotiator: 'harasawa',
    accuracy: '100%',
    expectedOrderDate: '2018/03/31',
    proposedPlan: 'Bプラン',
    option: {
      'オプション[sample1]': 1,
      'オプション[sample2]': 1,
      'オプション[sample3]': 0,
      'オプション[sample4]': 0,
    },
    planCost: 500000,
    optionCost: 100000,
    totalCost: 600000,
    updated: 'harasawa',
    created: 'harasawa',
    updatedAt: '2023/07/31 11:46',
    createdAt: '2023/07/31 11:46',
  },
  {
    id: 2,
    project: '金都運総研採用管理改革案件',
    client: '金都運総研',
    department: '情報システム部',
    pic: '下山 達士',
    detail: '採用部門での応募者管理の仕組みが非効率なので、\n少ない担当者で対応できるように、システム化をご希望。',
    firstMeetingDate: '2018/05/10',
    negotiator: 'harasawa',
    accuracy: '60%',
    expectedOrderDate: '2018/08/24',
    proposedPlan: 'Bプラン',
    option: {
      'オプション[sample1]': 0,
      'オプション[sample2]': 1,
      'オプション[sample3]': 0,
      'オプション[sample4]': 0,
    },
    planCost: 2000000,
    optionCost: 0,
    totalCost: 2000000,
    updated: 'harasawa',
    created: 'harasawa',
    updatedAt: '2023/07/31 11:46',
    createdAt: '2023/07/31 11:46',
  },
  {
    id: 3,
    project: '戸田ネットソリューションズ経費精算システム案件',
    client: '戸田ネットソリューションズ',
    department: '開発本部',
    pic: '川崎 丈史',
    firstMeetingDate: '2018/05/31',
    detail: '全社で利用する経費精算システムのリプレイスをご検討とのこと。',
    negotiator: 'harasawa',
    accuracy: '80%',
    expectedOrderDate: '2018/07/31',
    proposedPlan: 'Aプラン',
    option: {
      'オプション[sample1]': 0,
      'オプション[sample2]': 1,
      'オプション[sample3]': 0,
      'オプション[sample4]': 0,
    },
    planCost: 1500000,
    optionCost: 0,
    totalCost: 1500000,
    updated: 'harasawa',
    created: 'harasawa',
    updatedAt: '2023/07/31 11:46',
    createdAt: '2023/07/31 11:46',
  },
  {
    id: 4,
    project: '田端食品ワークフローシステム案件',
    client: '田端食品',
    department: '総務部',
    pic: '川越 憲一',
    firstMeetingDate: '2018/02/01',
    detail: '全社で利用するワークフローシステムを新規検討。',
    negotiator: 'harasawa',
    accuracy: '60%',
    expectedOrderDate: '2018/05/31',
    proposedPlan: 'Bプラン',
    option: {
      'オプション[sample1]': 0,
      'オプション[sample2]': 0,
      'オプション[sample3]': 1,
      'オプション[sample4]': 0,
    },
    planCost: 1200000,
    optionCost: 0,
    totalCost: 1200000,
    updated: 'harasawa',
    created: 'harasawa',
    updatedAt: '2023/07/31 11:46',
    createdAt: '2023/07/31 11:46',
  },
  {
    id: 5,
    project: '中川工業採用管理改革案件',
    client: '株式会社中川工業',
    department: '営業部',
    pic: '戸塚 璃子',
    firstMeetingDate: '2018/05/11',
    detail: '採用部門での応募者管理の仕組みが非効率なので、システム化をご希望。',
    negotiator: 'harasawa',
    accuracy: '20%',
    expectedOrderDate: '2018/08/24',
    proposedPlan: 'Bプラン',
    option: {
      'オプション[sample1]': 0,
      'オプション[sample2]': 0,
      'オプション[sample3]': 1,
      'オプション[sample4]': 0,
    },
    planCost: 1000000,
    optionCost: 0,
    totalCost: 1000000,
    updated: 'harasawa',
    created: 'harasawa',
    updatedAt: '2023/07/31 11:46',
    createdAt: '2023/07/31 11:46',
  },
  {
    id: 6,
    project: '池田学院大学ポータル案件',
    client: '池田学院大学',
    department: '情報システム部',
    pic: '小寺 樹里',
    firstMeetingDate: '2018/01/11',
    detail: '学内向けポータルの刷新案件。',
    negotiator: 'harasawa',
    accuracy: '40%',
    expectedOrderDate: '2018/03/31',
    proposedPlan: 'Bプラン',
    'オプション[sample1]': 1,
    'オプション[sample2]': '',
    'オプション[sample3]': '',
    'オプション[sample4]': '',
    planCost: 4500000,
    optionCost: 500000,
    totalCost: 5000000,
    updated: 'harasawa',
    created: 'harasawa',
    updatedAt: '2023/07/31 11:46',
    createdAt: '2023/07/31 11:46',
  },
  {
    id: 7,
    client: '寺島総合法律事務所',
    project: '寺島総合法律事務所経費精算システム案件',
    department: '営業部',
    pic: '星野 長利',
    firstMeetingDate: '2018/05/17',
    detail: '経費精算システムのリプレイスをご検討とのこと。',
    negotiator: 'harasawa',
    accuracy: '80%',
    expectedOrderDate: '2018/07/31',
    proposedPlan: 'Aプラン',
    option: {
      'オプション[sample1]': 0,
      'オプション[sample2]': 1,
      'オプション[sample3]': 0,
      'オプション[sample4]': 0,
    },
    planCost: 2500000,
    optionCost: 0,
    totalCost: 2500000,
    updated: 'harasawa',
    created: 'harasawa',
    updatedAt: '2023/07/31 11:46',
    createdAt: '2023/07/31 11:46',
  },
  {
    id: 8,
    project: '有限会社亀山営業支援ツール案件',
    client: '有限会社亀山',
    department: '経理部',
    pic: '上野 裕次郎',
    firstMeetingDate: '2018/01/24',
    detail: '法人向け営業チームにて、エクセル管理している案件管理、顧客管理をシステム化したい。\n納期は上期内をご希望。',
    negotiator: 'harasawa',
    accuracy: '100%',
    expectedOrderDate: '2018/06/30',
    proposedPlan: 'Bプラン',
    option: {
      'オプション[sample1]': 1,
      'オプション[sample2]': 0,
      'オプション[sample3]': 0,
      'オプション[sample4]': 0,
    },
    planCost: 500000,
    optionCost: 100000,
    totalCost: 600000,
    updated: 'harasawa',
    created: 'harasawa',
    updatedAt: '2023/07/31 11:46',
    createdAt: '2023/07/31 11:46',
  },
  {
    id: 9,
    project: '中丸建設採用管理改革案件',
    client: '中丸建設',
    department: '総務部',
    pic: '水谷 まなみ',
    detail: '採用部門での応募者管理の仕組みのシステム化をご希望。',
    firstMeetingDate: '2018/05/11',
    negotiator: 'harasawa',
    accuracy: '20%',
    expectedOrderDate: '2018/08/24',
    proposedPlan: 'Bプラン',
    option: {
      'オプション[sample1]': 0,
      'オプション[sample2]': 0,
      'オプション[sample3]': 1,
      'オプション[sample4]': 0,
    },
    planCost: 2000000,
    optionCost: 0,
    totalCost: 2000000,
    updated: 'harasawa',
    created: 'harasawa',
    updatedAt: '2023/07/31 11:46',
    createdAt: '2023/07/31 11:46',
  },
  {
    id: 10,
    project: 'ミヤタシステムズポータル案件',
    client: 'ミヤタシステムズ',
    department: 'ソリューション営業グループ',
    pic: '前原 勇',
    detail: '代理店向けポータルの新規導入案件。',
    firstMeetingDate: '2018/04/12',
    negotiator: 'harasawa',
    accuracy: '40%',
    expectedOrderDate: '2018/03/31',
    proposedPlan: 'Bプラン',
    option: { 'オプション[sample1]': 1,
      'オプション[sample2]': 0,
      'オプション[sample3]': 0,
      'オプション[sample4]': 0,
    },
    planCost: 3500000,
    optionCost: 500000,
    totalCost: 4000000,
    updated: 'harasawa',
    created: 'harasawa',
    updatedAt: '2023/07/31 11:46',
    createdAt: '2023/07/31 11:46',
  }
];

// 活動履歴データ
export const activityHistory = [
  {
    supportDate: '2018/05/30',
    supporter: 'harasawa',
    client: '金都運総研',
    project: '金都運総研採用管理改革案件',
    correspondence: '商談',
    note: '初回訪問して、ご検討内容をお伺いした。\nヒアリング内容を元に次回提案実施予定。',
    id: 1,
    updated: 'harasawa',
    created: 'harasawa',
    updatedAt: '2023/07/31 11:46',
    createdAt: '2023/07/31 11:46',
    department: '情報システム部',
    pic: '下山 達士',
    '案件管理レコード番号（関連レコード一覧紐付け用）': 2,
    '顧客管理レコード番号（関連レコード一覧紐付け用）': 20,
  },
  {
    supportDate: '2018/06/08',
    supporter: 'harasawa',
    client: '金都運総研',
    project: '金都運総研採用管理改革案件',
    correspondence: '商談',
    note: '前回ヒアリング内容を元に、提案を実施。\n大筋ご納得いただけたようなので、修正点を確認後\n概算見積もりを実施予定。',
    id: 2,
    updated: 'harasawa',
    created: 'harasawa',
    updatedAt: '2023/07/31 11:46',
    createdAt: '2023/07/31 11:46',
    department: '情報システム部',
    pic: '下山 達士',
    '案件管理レコード番号（関連レコード一覧紐付け用）': 2,
    '顧客管理レコード番号（関連レコード一覧紐付け用）': 20,
  },
  {
    supportDate: '2018/07/04',
    supporter: 'harasawa',
    client: '金都運総研',
    project: '金都運総研採用管理改革案件',
    correspondence: '見積提示',
    note: '概算見積もりを提示。',
    id: 3,
    updated: 'harasawa',
    created: 'harasawa',
    updatedAt: '2023/07/31 11:46',
    createdAt: '2023/07/31 11:46',
    department: '情報システム部',
    pic: '下山 達士',
    '案件管理レコード番号（関連レコード一覧紐付け用）': 2,
    '顧客管理レコード番号（関連レコード一覧紐付け用）': 20,
  },
  {
    supportDate: '2018/01/11',
    supporter: 'harasawa',
    client: '金都運総研',
    project: '金都運総研営業支援ツール案件',
    correspondence: '問い合わせ',
    note: '営業支援ツールを新規検討とのお問い合わせをいただいたので、お電話で質疑対応。\n次回はデモンストレーションを持って訪問予定。',
    id: 4,
    updated: 'harasawa',
    created: 'harasawa',
    updatedAt: '2023/07/31 11:46',
    createdAt: '2023/07/31 11:46',
    department: '情報システム部',
    pic: '下山 達士',
    '案件管理レコード番号（関連レコード一覧紐付け用）': 1,
    '顧客管理レコード番号（関連レコード一覧紐付け用）': 20,
  },
  {
    supportDate: '2018/01/24',
    supporter: 'harasawa',
    client: '金都運総研',
    project: '金都運総研営業支援ツール案件',
    correspondence: '商談',
    note: 'デモンストレーションを持って訪問。\nご要望内容と機能面のすり合わせを実施。',
    id: 5,
    updated: 'harasawa',
    created: 'harasawa',
    updatedAt: '2023/07/31 11:46',
    createdAt: '2023/07/31 11:46',
    department: '情報システム部',
    pic: '下山 達士',
    '案件管理レコード番号（関連レコード一覧紐付け用）': 1,
    '顧客管理レコード番号（関連レコード一覧紐付け用）': 20,
  },
  {
    supportDate: '2018/02/08',
    supporter: 'harasawa',
    client: '金都運総研',
    project: '金都運総研営業支援ツール案件',
    correspondence: '商談',
    note: 'すり合わせを持ってして再度ご提案とデモ。\n合意を得られたので、お見積もり作成して提示へ。',
    id: 6,
    updated: 'harasawa',
    created: 'harasawa',
    updatedAt: '2023/07/31 11:46',
    createdAt: '2023/07/31 11:46',
    department: '情報システム部',
    pic: '下山 達士',
    '案件管理レコード番号（関連レコード一覧紐付け用）': 1,
    '顧客管理レコード番号（関連レコード一覧紐付け用）': 20,
  },
  {
    supportDate: '2018/03/01',
    supporter: 'harasawa',
    client: '金都運総研',
    project: '金都運総研営業支援ツール案件',
    correspondence: '見積提示',
    note: '見積もり提示。お客さまの稟議を待って、ご発注いただける予定。',
    id: 7,
    updated: 'harasawa',
    created: 'harasawa',
    updatedAt: '2023/07/31 11:46',
    createdAt: '2023/07/31 11:46',
    department: '情報システム部',
    pic: '下山 達士',
    '案件管理レコード番号（関連レコード一覧紐付け用）': 1,
    '顧客管理レコード番号（関連レコード一覧紐付け用）': 20,
  },
  {
    supportDate: '2018/03/07',
    supporter: 'harasawa',
    client: '金都運総研',
    project: '金都運総研営業支援ツール案件',
    correspondence: '注文書回収',
    note: 'ご発注書を回収。アフターフォローそ進めていく体制を検討する。',
    id: 8,
    updated: 'harasawa',
    created: 'harasawa',
    updatedAt: '2023/07/31 11:46',
    createdAt: '2023/07/31 11:46',
    department: '情報システム部',
    pic: '下山 達士',
    '案件管理レコード番号（関連レコード一覧紐付け用）': 1,
    '顧客管理レコード番号（関連レコード一覧紐付け用）': 20,
  },
  {
    supportDate: '2018/05/31',
    supporter: 'harasawa',
    client: '戸田ネットソリューションズ',
    project: '戸田ネットソリューションズ経費精算システム案件',
    correspondence: '商談',
    note: '現状の経費精算システムの利用状況、機能要件をヒアリング。',
    id: 9,
    updated: 'harasawa',
    created: 'harasawa',
    updatedAt: '2023/07/31 11:46',
    createdAt: '2023/07/31 11:46',
    department: '開発本部',
    pic: '川崎 丈史',
    '案件管理レコード番号（関連レコード一覧紐付け用）': 3,
    '顧客管理レコード番号（関連レコード一覧紐付け用）': 19,
  },
  {
    supportDate: '2018/07/31',
    supporter: 'harasawa',
    client: '戸田ネットソリューションズ',
    project: '戸田ネットソリューションズ経費精算システム案件',
    department: '開発本部',
    pic: '川崎 丈史',
    correspondence: '商談',
    note:'現状の経費精算システムの利用状況、機能要件を元に、\n新システムに求める機能要件を洗い出し。',
    id: 10,
    updated: 'harasawa',
    created: 'harasawa',
    updatedAt: '2023/07/31 11:46',
    createdAt: '2023/07/31 11:46',
    '案件管理レコード番号（関連レコード一覧紐付け用）': 3,
    '顧客管理レコード番号（関連レコード一覧紐付け用）': 19,
  },
  {
    supportDate: '2018/06/01',
    supporter: 'harasawa',
    client: '株式会社中川工業',
    project: '中川工業採用管理改革案件',
    correspondence: '商談',
    note: '初回訪問して、ご検討内容をお伺いした。\nヒアリング内容を元に次回提案実施予定。',
    id: 11,
    updated: 'harasawa',
    created: 'harasawa',
    updatedAt: '2023/07/31 11:46',
    createdAt: '2023/07/31 11:46',
    department: '営業部',
    pic: '戸塚 璃子',
    '案件管理レコード番号（関連レコード一覧紐付け用）': 5,
    '顧客管理レコード番号（関連レコード一覧紐付け用）': 17,
  },
  {
    supportDate: '2018/06/15',
    supporter: 'harasawa',
    client: '株式会社中川工業',
    project: '中川工業採用管理改革案件',
    correspondence: '商談',
    note: 'ヒアリングを元に、提案とデモを実施。\n修正点を確認後、概算見積もりを実施予定。',
    id: 12,
    updated: 'harasawa',
    created: 'harasawa',
    updatedAt: '2023/07/31 11:46',
    createdAt: '2023/07/31 11:46',
    department: '営業部',
    pic: '戸塚 璃子',
    '案件管理レコード番号（関連レコード一覧紐付け用）': 5,
    '顧客管理レコード番号（関連レコード一覧紐付け用）': 17,
  },
  {
    supportDate: '2018/01/25',
    supporter: 'harasawa',
    client: '寺島総合法律事務所',
    project: '寺島総合法律事務所経費精算システム案件',
    correspondence: '商談',
    note: '提案書を用意して訪問。\nご要望内容と機能面のすり合わせを実施。',
    id: 13,
    updated: 'harasawa',
    created: 'harasawa',
    updatedAt: '2023/07/31 11:46',
    createdAt: '2023/07/31 11:46',
    department: '営業部',
    pic: '星野 長利',
    '案件管理レコード番号（関連レコード一覧紐付け用）': 7,
    '顧客管理レコード番号（関連レコード一覧紐付け用）': 15,
  },
  {
    supportDate: '2018/02/02',
    supporter: 'harasawa',
    client: '有限会社亀山',
    project: '有限会社亀山営業支援ツール案件',
    correspondence: '商談',
    note: '現状の運用についてヒアリングを実施。今後提案を固めていく。',
    id: 14,
    updated: 'harasawa',
    created: 'harasawa',
    updatedAt: '2023/07/31 11:46',
    createdAt: '2023/07/31 11:46',
    department: '経理部',
    pic: '上野 裕次郎',
    '案件管理レコード番号（関連レコード一覧紐付け用）': 8,
    '顧客管理レコード番号（関連レコード一覧紐付け用）': 14,
  },

  {
    supportDate: '2018/05/24',
    supporter: 'harasawa',
    client: '中丸建設',
    project: '中丸建設採用管理改革案件',
    correspondence: '商談',
    note: 'As-Isのヒアリングを実施。\nコンサルティングを交えた提案を検討していく。',
    id: 15,
    updated: 'harasawa',
    created: 'harasawa',
    updatedAt: '2023/07/31 11:46',
    createdAt: '2023/07/31 11:46',
    department: '総務部',
    pic: '水谷 まなみ',
    '案件管理レコード番号（関連レコード一覧紐付け用）': 9,
    '顧客管理レコード番号（関連レコード一覧紐付け用）': 13,
  },
  {
    supportDate: '2018/04/12',
    supporter: 'harasawa',
    client: 'ミヤタシステムズ',
    project: 'ミヤタシステムズポータル案件',
    correspondence: 'セミナー',
    note: '社内情報共有の活性化セミナーにご来場されて、個別相談実施。',
    id: 16,
    updated: 'harasawa',
    created: 'harasawa',
    updatedAt: '2023/07/31 11:46',
    createdAt: '2023/07/31 11:46',
    department: 'ソリューション営業グループ',
    pic: '前原 勇',
    '案件管理レコード番号（関連レコード一覧紐付け用）': 10,
    '顧客管理レコード番号（関連レコード一覧紐付け用）': 12,
  },
  {
    supportDate: '2018/06/29',
    supporter: 'harasawa',
    client: '株式会社中川工業',
    project: '中川工業採用管理改革案件',
    correspondence: '見積提示',
    note: '概算見積もりを提示。お客様に社内検討を進めていただく。',
    id: 17,
    updated: 'harasawa',
    created: 'harasawa',
    updatedAt: '2023/07/31 11:46',
    createdAt: '2023/07/31 11:46',
    department: '営業部',
    pic: '戸塚 璃子',
    '案件管理レコード番号（関連レコード一覧紐付け用）': 5,
    '顧客管理レコード番号（関連レコード一覧紐付け用）': 17,
  },
  {
    supportDate: '2018/04/26',
    supporter: 'harasawa',
    client: 'ミヤタシステムズ',
    project: 'ミヤタシステムズポータル案件',
    correspondence: '商談',
    note: 'ポータルのご検討内容と展望を再度ヒアリング。機能要件に落として提案。',
    id: 18,
    updated: 'harasawa',
    created: 'harasawa',
    updatedAt: '2023/07/31 11:46',
    createdAt: '2023/07/31 11:46',
    department: 'ソリューション営業グループ',
    pic: '前原 勇',
    '案件管理レコード番号（関連レコード一覧紐付け用）': 10,
    '顧客管理レコード番号（関連レコード一覧紐付け用）': 12,
  },
  {
    supportDate: '2018/03/22',
    supporter: 'harasawa',
    client: '池田学院大学',
    project: '池田学院大学ポータル案件',
    correspondence: 'ご挨拶',
    note: '上長とご挨拶にお伺い。',
    id: 19,
    updated: 'harasawa',
    created: 'harasawa',
    updatedAt: '2023/07/31 11:46',
    createdAt: '2023/07/31 11:46',
    department: '情報システム部',
    pic: '小寺 樹里',
    '案件管理レコード番号（関連レコード一覧紐付け用）': 6,
    '顧客管理レコード番号（関連レコード一覧紐付け用）': 16,
  },
  {
    supportDate: '2018/03/29',
    supporter: 'harasawa',
    client: '田端食品',
    project: '田端食品ワークフローシステム案件',
    correspondence: '商談',
    note: '現状の業務フローをヒアリング。',
    id: 20,
    updated: 'harasawa',
    created: 'harasawa',
    updatedAt: '2023/07/31 11:46',
    createdAt: '2023/07/31 11:46',
    department: '総務部',
    pic: '川越 憲一',
    '案件管理レコード番号（関連レコード一覧紐付け用）': 4,
    '顧客管理レコード番号（関連レコード一覧紐付け用）': 18,
  },
];

// 顧客データ
export const clientData = [
  {
    id: 1,
    client: '金都運総研',
    department: '情報システム部',
    tel: '090-0000-1111',
    email: 'shimoyama_tatsuhito@example.com',
    zip: 5010001,
    address: '岐阜県岐阜市××××',
    pic: '下山 達士',
    fax: '050-××××-××××',
    note: '',
    created: 'harasawa',
    updated: 'harasawa',
    updatedAt: '2023/07/31 11:46',
    createdAt: '2023/07/31 11:46',
  },
  {
    id: 2,
    client: '戸田ネットソリューションズ',
    department: '開発本部',
    tel: '092-2222-3333',
    email: 'kawasaki_takeshi@example.com',
    zip: 3200001,
    address: '栃木県宇都宮市××××',
    pic: '川崎 丈史',
    note: '',
    created: 'harasawa',
    updated: 'harasawa',
    updatedAt: '2023/07/31 11:46',
    createdAt: '2023/07/31 11:46',
  },
  {
    id: 3,
    client: '田端食品',
    department: '総務部',
    tel: '050-1314-1231',
    email: 'kawagoe_kenichi@example.com',
    zip: 3300041,
    address: '埼玉県浦和市××××',
    pic: '川越 憲一',
    note: '',
    created: 'harasawa',
    updated: 'harasawa',
    updatedAt: '2023/07/31 11:46',
    createdAt: '2023/07/31 11:46',
  },
  {
    id: 4,
    client: '株式会社中川工業',
    department: '営業部',
    tel: '042-5567-3421',
    email: 'toduka_riko@example.com',
    zip: 4130001,
    address: '静岡県熱海市××××',
    pic: '戸塚 璃子',
    note: '',
    created: 'harasawa',
    updated: 'harasawa',
    updatedAt: '2023/07/31 11:46',
    createdAt: '2023/07/31 11:46',
  },
  {
    id: 5,
    client: '池田学院大学',
    department: '情報システム部',
    tel: '090-1251-8876',
    email: 'kodera_juri@example.com',
    zip: 2500001,
    address: '神奈川県小田原市××××',
    pic: '小寺 樹里',
    note: '',
    created: 'harasawa',
    updated: 'harasawa',
    updatedAt: '2023/07/31 11:46',
    createdAt: '2023/07/31 11:46',
  },
  {
    id: 6,
    client: '寺島総合法律事務所',
    department: '営業部',
    tel: '090-2131-1318',
    email: 'hoshino_nagatoshi@example.com',
    zip: 3700001,
    address: '群馬県前橋市××××',
    pic: '星野 長利',
    note: '',
    created: 'harasawa',
    updated: 'harasawa',
    updatedAt: '2023/07/31 11:46',
    createdAt: '2023/07/31 11:46',
  },
  {
    id: 7,
    client: '有限会社亀山',
    department: '経理部',
    tel: '090-6754-1412',
    email: 'ueno_yuujirou@example.com',
    zip: 5300001,
    address: '大阪府大阪市北区梅田××××',
    pic: '上野 裕次郎',
    note: '',
    created: 'harasawa',
    updated: 'harasawa',
    updatedAt: '2023/07/31 11:46',
    createdAt: '2023/07/31 11:46',
  },
  {
    id: 8,
    client: '中丸建設',
    department: '総務部',
    tel: '090-1212-1212',
    email: 'mizutani_manami@example.com',
    zip: 9500001,
    address: '新潟県新潟市××××',
    pic: '水谷 まなみ',
    note: '',
    created: 'harasawa',
    updated: 'harasawa',
    updatedAt: '2023/07/31 11:46',
    createdAt: '2023/07/31 11:46',
  },
  {
    id: 9,
    client: 'ミヤタシステムズ',
    department: 'ソリューション営業グループ',
    tel: '090-1212-1212',
    email: 'maehara_yuu@example.com',
    zip: 6540001,
    address: '兵庫県神戸市須磨区1212',
    pic: '前原 勇',
    note: '',
    created: 'harasawa',
    updated: 'harasawa',
    updatedAt: '2023/07/31 11:46',
    createdAt: '2023/07/31 11:46',
  },
  {
    id: 10,
    client: '塚本ソフトウェア',
    department: '開発本部',
    tel: '090-1111-1111',
    email: 'iwasawa_tomoya@example.com',
    zip: 1660001,
    address: '東京都杉並区××××',
    pic: '岩沢 友也',
    note: '',
    created: 'harasawa',
    updated: 'harasawa',
    updatedAt: '2023/07/31 11:46',
    createdAt: '2023/07/31 11:46',
  },
  {
    id: 11,
    client: '千葉コールセンター',
    department: '総務部',
    tel: '090-1212-1212',
    email: 'matsuno_ami@example.com',
    zip: 3200001,
    address: '栃木県宇都宮市××××',
    pic: '松野 有海',
    note: '',
    created: 'harasawa',
    updated: 'harasawa',
    updatedAt: '2023/07/31 11:46',
    createdAt: '2023/07/31 11:46',
  },
  {
    id: 12,
    client: '仲間建材工業',
    department: '営業部',
    tel: '090-1212-1212',
    email: 'ozaki_takahiro@example.com',
    zip: 3200001,
    address: '栃木県宇都宮市××××',
    pic: '尾崎 隆博',
    note: '',
    created: 'harasawa',
    updated: 'harasawa',
    updatedAt: '2023/07/31 11:46',
    createdAt: '2023/07/31 11:46',
  },
  {
    id: 13,
    client: '株式会社井上技研',
    department: '情報システム部',
    tel: '090-1212-1212',
    email: 'yoshizawa_shidou@example.com',
    zip: 4130001,
    address: '静岡県熱海市××××',
    pic: '吉沢 獅童',
    note: '',
    created: 'harasawa',
    updated: 'harasawa',
    updatedAt: '2023/07/31 11:46',
    createdAt: '2023/07/31 11:46',
  },
  {
    id: 14,
    client: '鈴木土地建物',
    department: '第二営業部',
    tel: '090-0011-0011',
    email: 'yonezawa_sachie@example.com',
    zip: 2500001,
    address: '神奈川県小田原市××××',
    pic: '米沢 沙知絵',
  },
  {
    id: 15,
    client: '草刈組',
    department: '総務部',
    tel: '090-9090-9090',
    email: 'harada_chiemi@example.com',
    zip: 6000001,
    address: '京都府京都市××××',
    pic: '原田 ちえみ',
    note: '',
    created: 'harasawa',
    updated: 'harasawa',
    updatedAt: '2023/07/31 11:46',
    createdAt: '2023/07/31 11:46',
  },
  {
    id: 16,
    client: '岡崎商会',
    department: 'ソリューション営業グループ',
    tel: '090-9090-9090',
    email: 'kiyota_seiichi@example.com',
    zip: 1660001,
    address: '東京都杉並区××××',
    pic: '清田 誠一',
    note: '',
    created: 'harasawa',
    updated: 'harasawa',
    updatedAt: '2023/07/31 11:46',
    createdAt: '2023/07/31 11:46',
  },
  {
    id: 17,
    client: '岩下税理士事務所',
    department: '情報システム部',
    tel: '090-9898-9898',
    email: 'sasaki_juri@example.com',
    zip: 6540001,
    address: '兵庫県神戸市須磨区××××',
    pic: '佐々木 樹里',
    note: '',
    created: 'harasawa',
    updated: 'harasawa',
    updatedAt: '2023/07/31 11:46',
    createdAt: '2023/07/31 11:46',
  },
  {
    id: 18,
    client: '新山物産',
    department: '営業本部第一営業部',
    tel: '090-4343-4343',
    email: 'kaneko_maho@example.com',
    zip: 5300001,
    address: '大阪府大阪市北区梅田××××',
    pic: '金子 真帆',
    note: '',
    created: 'harasawa',
    updated: 'harasawa',
    updatedAt: '2023/07/31 11:46',
    createdAt: '2023/07/31 11:46',
  },
  {
    id: 19,
    client: '板橋電子株式会社',
    department: '経理部',
    tel: '090-1313-1313',
    email: 'suenaga_yuri@example.com',
    zip: 2500001,
    address: '神奈川県小田原市1313',
    pic: '末永 妃里',
    note: '',
    created: 'harasawa',
    updated: 'harasawa',
    updatedAt: '2023/07/31 11:46',
    createdAt: '2023/07/31 11:46',
  },
  {
    id: 20,
    client: '林田商会',
    department: 'ソリューション営業グループ',
    tel: '090-7777-7777',
    email: 'mori_jun@example.com',
    zip: 3300041,
    address: '埼玉県浦和市××××',
    pic: '森 惇',
    note: '',
    created: 'harasawa',
    updated: 'harasawa',
    updatedAt: '2023/07/31 11:46',
    createdAt: '2023/07/31 11:46',
  },
];
